### ISSUE TITLE
workflow tab saving

### ISSUE THREAD

**Issue by midol** [mdreier/savetabs#15]
Martin,

A good add-on. Today I'm working on  a project that I only have time for once in a while. I'd like to save my tabs to a folder along with other relevant project files then reopen the tabs the next time I work on it. I can fake it with bookmarks but an enhancement to savetabs would be better. Is this on the horizon? Or can you consider this a feature request?

Dave

**Comment by mdreier** [comment]
Hi @midol, unfortunately it is not allowed for Firefox add-ons to read/write files, therefor it is currently not possible to implement such a feature. Sorry for the bad news.
