### ISSUE TITLE
Saved Tabs Won't Overwrite

### ISSUE THREAD

**Issue by gentisle** [mdreier/savetabs#21]
Whenever I save tabs, it does not save new tab info. But it does, sort of. It seems to be saving two sets of tabs apparently in two differing locations. The original saved tab info only comes up after a crash, or after some arrogant browser launching program launches my browser with only one tab. Then upon restoring the tabs, Save Tabs brings up all the original tabs, not my most current list. Where are those file saved so I can delete them so they will never return? Thanks.

**Comment by mdreier** [comment]
So, I finally got around to looking into this issue. Sorry that it took so long.

First of all, the saved tabs are stored in the local storage available to the extension. The [storage.local documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) makes no mention where the data is actually persisted, but at least in my case it is stored in a database inside the browser's user profile.

Regarding your issue, it's probably related to #24. In a previous version I changed the layout of the storage to account for group. However, after migration I forgot to empty the old storage location. I don't know why it re-reads it after a crash, but this is probably why it's coming up again for you. So I hope this issue will be solved once the other bug is fixed.
