### ISSUE TITLE
completely stopped working

### ISSUE THREAD

**Issue by distresseddamsel** [mdreier/savetabs#22]
On the newest version of firefox the widget stopped working entirely, you can't see your saved tabs, you can't save new tabs, and you cannot access any of the options for the app.

**Comment by mdreier** [comment]
Thank you for the report, I noticed it too. Seems that Firefox changed something about the loading of scripts. I’ll check it out ASAP.

**Comment by mdreier** [comment]
I fixed the issue and submitted a new version to Mozilla. I hope it will be released soon,

**Comment by distresseddamsel** [comment]
Thank you 😊
